# Generated by Django 4.0.1 on 2022-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_post_options_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
